package com.rs3voiceovers.sound;

import lombok.Getter;

public enum Sound {
    // TzKal-Zuk
    ZUK_FIRST_WAVE_1("TzKal-Zuk_-_A_challenger_approaches....wav"),
    ZUK_FIRST_WAVE_2("TzKal-Zuk_-_What_makes_you_think_you_have_what_it_takes.wav"),
    ZUK_RELOG("TzKal-Zuk_-_Interesting..._you_return.wav"),
    ZUK_WAVES_1("TzKal-Zuk_-_Show_me_you_are_worthy!.wav"),
    ZUK_WAVES_2("TzKal-Zuk_-_Fight,_worm!_Or_crawl_and_die!.wav"),
    ZUK_WAVES_3("TzKal-Zuk_-_To_the_slaughter!.wav"),
    ZUK_WAVES_4("TzKal-Zuk_-_Prove_your_worth.wav"),
    ZUK_WAVES_5("TzKal-Zuk_-_Charge!.wav"),
    ZUK_WAVES_6("TzKal-Zuk_-_Into_the_fray!.wav"),
    ZUK_WAVES_7("TzKal-Zuk_-_The_unworthy_will_burn.wav"),
    ZUK_WAVES_8("TzKal-Zuk_-_All_of_you__attack_.wav"),
    ZUK_WAVES_9("TzKal-Zuk_-_Rise,_scions_of_the_Kiln!.wav"),
    ZUK_WAVES_10("TzKal-Zuk_-_Fight_or_die!.wav"),
    ZUK_WAVES_11("TzKal-Zuk_-_Die,_and_be_reborn_in_flame!.wav"),
    ZUK_WAVES_12("TzKal-Zuk_-_To_ashes_.wav"),
    ZUK_START_1("TzKal-Zuk_-_Now_-_the_true_battle_begins!.wav"),
    ZUK_START_2("TzKal-Zuk_-_Out_of_the_way,_weaklings!.wav"),
    ZUK_START_3("TzKal-Zuk_-_Perhaps_you_are_worthy.wav"),
    ZUK_FIGHT_1("TzKal-Zuk_-_Drag_them_to_the_molten_deep!.wav"),
    ZUK_FIGHT_2("TzKal-Zuk_-_Flames_unending....wav"),
    ZUK_FIGHT_3("TzKal-Zuk_-_Break_beneath_me.wav"),
    ZUK_FIGHT_4("TzKal-Zuk_-_Tremble_before_me.wav"),
    ZUK_FIGHT_5("TzKal-Zuk_-_Suffer_.wav"),
    ZUK_FIGHT_6("TzKal-Zuk_-_Sear_.wav"),
    ZUK_FIGHT_7("TzKal-Zuk_-_Burn!.wav"),
    ZUK_FIGHT_8("TzKal-Zuk_-_Die_.wav"),
    ZUK_FIGHT_9("TzKal-Zuk_-_Flames_consume_you_.wav"),
    ZUK_FIGHT_10("TzKal-Zuk_-_Fall__and_burn_to_ash_.wav"),
    ZUK_FIGHT_11("TzKal-Zuk_-_Be_scourged_by_flame!.wav"),
    ZUK_FIGHT_12("TzKal-Zuk_-_Begone!.wav"),
    ZUK_FIGHT_13("TzKal-Zuk_-_Ful_s_flame_burns_within_me_.wav"),
    ZUK_FIGHT_14("TzKal-Zuk_-_Burn_to_nothing!.wav"),
    ZUK_ENRAGED_1("TzKal-Zuk_-_This_has_gone_on_too_long_-_kill_them!.wav"),
    ZUK_ENRAGED_2("TzKal-Zuk_-_I_grow_weary_of_this._End_it_quickly.wav"),
    ZUK_VICTORY_1("TzKal-Zuk_-_Impossible....wav"),
    ZUK_VICTORY_2("TzKal-Zuk_-_Not..._since_Bandos....wav"),
    ZUK_VICTORY_3("TzKal-Zuk_-_Finally..._After_thousands_of_years....wav"),
    ZUK_DEFEAT_1("TzKal-Zuk_-_Pathetic.wav"),
    ZUK_DEFEAT_2("TzKal-Zuk_-_Worthless._Just_like_the_rest.wav"),
    ZUK_DEFEAT_3("TzKal-Zuk_-_You_have_failed,_as_expected.wav"),
    ZUK_JAD_1("TzKal-Zuk_-_Rise_Jad!.wav"),
    ZUK_JAD_2("TzKal-Zuk_-_Unleash_Jad!.wav"),
    ZUK_JAD_3("TzKal-Zuk_-_Enough._Jad_will_end_this.wav"),
    ZUK_JAD_VICTORY_1("TzKal-Zuk_-_Ungh._not_bad...wav"),
    ZUK_JAD_VICTORY_2("TzKal-Zuk_-_A_champion_rises.wav"),
    ZUK_JAD_VICTORY_3("TzKal-Zuk_-_You_have_earned_your_right_to_live._For_now.wav"),
    ZUK_JAD_VICTORY_4("TzKal-Zuk_-_Hmph._Interesting...wav"),
    ZUK_JAD_VICTORY_5("TzKal-Zuk_-_It_appears_you_have_exceeded_my_expectations.wav"),
    ZUK_JAD_VICTORY_6("TzKal-Zuk_-_Not...so_weak_as_you_seem.wav"),


    // Zemouregal (and Vorkath)
    VORKATH_START_1("Zemouregal_-_Obey_your_master,_you_dumb_puppet.wav"),
    VORKATH_START_2("Zemouregal_-_The_dragon_WILL_be_mine!.wav"),
    VORKATH_START_3("Zemouregal_-_Rise_you_cursed_weakling,_I_shan't_tell_you_again!.wav"),
    VORKATH_COMMON_1("Zemouregal_-_Your_struggle__like_your_life__is_meaningless.wav"),
    VORKATH_COMMON_2("Zemouregal_-_No-one_can_stand_against_my_mighty_Undead!.wav"),
    VORKATH_COMMON_3("Zemouregal_-_No_escape.wav"),
    VORKATH_COMMON_4("Zemouregal_-_You_WILL_yield_to_my_might!.wav"),
    VORKATH_COMMON_5("Zemouregal_-_Be_gone,_gnawing_pest!.wav"),
    VORKATH_COMMON_6("Zemouregal_-_You_will_be_one_with_my_undead_troops.wav"),
    VORKATH_COMMON_7("Zemouregal_-_These_are_your_final_moments,_halfwit!.wav"),
    VORKATH_COMMON_8("Zemouregal_-_I'll_make_a_feast_of_your_blood_and_be_strengthened!.wav"),
    VORKATH_COMMON_9("Zemouregal_-_Why_do_you_bother_to_test_me_.wav"),
    VORKATH_COMMON_10("Zemouregal_-_You_thought_you_were_a_match_for_my_majesty_.wav"),
    VORKATH_COMMON_11("Zemouregal_-_I_shall_rend_the_very_flesh_from_your_bones!.wav"),
    VORKATH_COMMON_12("Zemouregal_-_Pah!_Pitiful.wav"),
    VORKATH_UNCOMMON_1("Zemouregal_-_This_piteous_joke_ends_now.wav"),
    VORKATH_UNCOMMON_2("Zemouregal_-_DIE!.wav"),
    VORKATH_UNCOMMON_3("Zemouregal_-_Say_farewell.wav"),
    VORKATH_UNCOMMON_4("Zemouregal_-_Cut_them_down_without_mercy!.wav"),
    VORKATH_UNCOMMON_5("Zemouregal_-_Cast_my_glorious_vengeance_down_upon_them!.wav"),
    VORKATH_POISON_1("Zemouregal_-_Suffocate_this_land_with_bile!.wav"),
    VORKATH_POISON_2("Zemouregal_-_Spew_your_venom,_my_malformed_pet!.wav"),
    VORKATH_POISON_3("Zemouregal_-_YES,_Heal the dumb beast!.wav"),
    VORKATH_POISON_4("Zemouregal_-_Drown_in_your_own_gore!.wav"),
    VORKATH_VICTORY_1("Zemouregal_-_Bah!_Useless!.wav"),
    VORKATH_VICTORY_2("Zemouregal_-_Are_you_determined_to_fail_.wav"),
    VORKATH_VICTORY_3("Zemouregal_-_GET_UP!_-_Why_must_you_test_my_patience_.wav"),
    VORKATH_VICTORY_4("Zemouregal_-_Urgh,_must_I_be_forever_plagued_by_lesser_beings_.wav"),
    VORKATH_VICTORY_5("Zemouregal_-_Inadequate_failure.wav"),
    VORKATH_DEFEAT_1("Zemouregal_-_Say_hello_to_Death_for_me!.wav"),
    VORKATH_DEFEAT_2("Zemouregal_-_Death_is,_quite_frankly,_too_good_for_you.wav"),
    VORKATH_DEFEAT_3("Zemouregal_-_Finally,_an_end_to_your_meddling.wav"),
    VORKATH_DEFEAT_4("Zemouregal_-_Death_protects_you__I_meant_to_have_you_for_my_own...wav"),
    VORKATH_DEFEAT_5("Zemouregal_-_Your_life_is_payment_for_this_folly!.wav"),

    // Amascut
    AMASCUT_START_1("Amascut_-_Destruction._Annihilation._My_vision_for_this_world.wav"),
    AMASCUT_START_2("Amascut_-_How_close_it_came_to_becoming_a_reality.wav"),
    AMASCUT_START_3("Amascut_-_Picture_the_heroes_who_would_have_risen_against_me.wav"),
    AMASCUT_START_4("Amascut_-_The_challenges_they_would_have_overcome.wav"),
    AMASCUT_START_5("Amascut_-_And_the_rewards_they_would_have_reaped.wav"),
    AMASCUT_START_6("Amascut_-_Who_among_you_is_worthy_of_facing_a_goddess_.wav"),
    AMASCUT_START_7("Amascut_-_Show_me....wav"),
    AMASCUT_TELEPORT_1("Amascut_-_The_mice_fight_back....wav"),
    AMASCUT_TELEPORT_2("Amascut_-_You_dare_to_turn_your_back_on_me_.wav"),
    AMASCUT_OBELISK_1("Amascut_-_Bend_the_knee.wav"),
    AMASCUT_OBELISK_2("Amascut_-_Grovel.wav"),
    AMASCUT_OBELISK_3("Amascut_-_Pathetic.wav"),
    AMASCUT_OBELISK_4("Amascut_-_Weak.wav"),
    AMASCUT_P2_1("Amascut_-_Tear_them_apart.wav"),
    AMASCUT_P2_2("Amascut_-_Even_with_your_strength_combined,_you_cannot_stop_me.wav"),
    AMASCUT_P2_3("Amascut_-_Resourcefulness_will_not_save_you.wav"),
    AMASCUT_P2_4("Amascut_-_I_am_a_god!.wav"),
    AMASCUT_P2_5("Amascut_-_Death_is_the_only_peace.wav"),
    AMASCUT_P2_6("Amascut_-_Your_companions_will_betray_you..._they_always_do.wav"),
    AMASCUT_ARCANE_1("Amascut_-_All_strength_withers.wav"),
    AMASCUT_ARCANE_2("Amascut_-_I_will_not_suffer_this.wav"),
    AMASCUT_ARCANE_3("Amascut_-_Your_soul_is_WEAK.wav"),
    AMASCUT_P2_END_1("Amascut_-_I_will_not_be_denied.wav"),
    AMASCUT_P2_END_2("Amascut_-_I_WILL_NOT_BE_SUBJUGATED_BY_A_MORTAL!.wav"),
    AMASCUT_P2_END_3("Amascut_-_It_is_NOT_over!.wav"),
    AMASCUT_P2_END_4("Amascut_-_ENOUGH.wav"),
    AMASCUT_P2_END_5("Amascut_-_Fall_to_the_shadow.wav"),
    AMASCUT_P2_END_6("Amascut_-_You_are_nothing!.wav"),
    AMASCUT_P2_END_7("Amascut_-_Mwahahaha.wav"),
    AMASCUT_P3_START_1("Amascut_-_Watch_as_this_vision_becomes_reality.wav"),
    AMASCUT_P3_START_2("Amascut_-_Behold!_The_fate_of_this_world.wav"),
    AMASCUT_P3_START_3("Amascut_-_Prove_that_you_have_the_will_to_stand_against_the_vision_of_a_goddess!.wav"),
    AMASCUT_P3_START_4("Amascut_-_I_will_tear_this_world_asunder!.wav"),
    AMASCUT_P3_START_5("Amascut_-_Let_us_see_if_these_delusions_of_grandeur_can_withstand_The_Devourers_maw.wav"),
    AMASCUT_P3_START_6("Amascut_-_Behold_the_inevitable_future!.wav"),
    AMASCUT_P3_MONOLOGUE_1("Amascut_-_It_is_not_merely_my_power_you_face!.wav"),
    AMASCUT_P3_MONOLOGUE_2("Amascut_-_Het...Scabaras...Bear_witness!.wav"),
    AMASCUT_P3_MONOLOGUE_3("Amascut_-_Bring_forth_Crondis_and_Apmeken.wav"),
    AMASCUT_P3_MONOLOGUE_4("Amascut_-_There_can_be_no_light_without_darkness!.wav"),
    AMASCUT_P3_MONOLOGUE_5("Amascut_-_Your_light_will_be_snuffed_out,_once_and_for_all.wav"),
    AMASCUT_P3_MONOLOGUE_6("Amascut_-_Our_father_will_be_reborn!.wav"),
    AMASCUT_P3_MONOLOGUE_7("Amascut_-_His_soul_will_be_judged_and_condemned!.wav"),
    AMASCUT_P3_MONOLOGUE_8("Amascut_-_I_will_have_my_vengeance!.wav"),
    AMASCUT_P3_MONOLOGUE_9("Amascut_-_Tumeken's_heart_I_will_claw_it_out_myself_if_I_have_to.wav"),
    AMASCUT_P3_MONOLOGUE_10("Amascut_-_Was_I_nothing_to_him.wav"),
    AMASCUT_P3_MONOLOGUE_11("Amascut_-_So_be_it....wav"),
    AMASCUT_P3_MONOLOGUE_12("Amascut_-_Come,_mortal.wav"),
    AMASCUT_P3_MONOLOGUE_13("Amascut_-_If_I_cannot_judge_his_soul,_then_I_will_condemn_yours_in_its_place.wav"),
    AMASCUT_P3_MONOLOGUE_14("Amascut_-_I_am_the_one_who_devours.wav"),
    AMASCUT_P3_MONOLOGUE_15("Amascut_-_I_AM.wav"),
    AMASCUT_P3_MONOLOGUE_16("Amascut_-_THE_GOD.wav"),
    AMASCUT_P3_MONOLOGUE_17("Amascut_-_OF.wav"),
    AMASCUT_P3_MONOLOGUE_18("Amascut_-_DESTRUCTION.wav"),
    AMASCUT_P3_MONOLOGUE_19("Amascut_-_DESTRUCTION_2.wav"),
    AMASCUT_P3_MONOLOGUE_20("Amascut_-_DESTRUCTION_3.wav"),
    AMASCUT_VICTORY_1("Amascut_-_Impossible....wav"),
    AMASCUT_VICTORY_2("Amascut_-_This_cannot_be_the_end....wav"),
    AMASCUT_VICTORY_3("Amascut_-_NO!.wav"),
    AMASCUT_DEFEAT_1("Amascut_-_Unworthy!.wav"),
    AMASCUT_DEFEAT_2("Amascut_-_There_is_no_place_1.wav"),
    AMASCUT_DEFEAT_3("Amascut_-_Your_souls_are_mine!.wav"),

    // General Graardor
    GRAARDOR_OVERHEAD_1("Graardor_-_All_glory_to_Bandos.wav"),
    GRAARDOR_OVERHEAD_2("Graardor_-_Brargh!.wav"),
    GRAARDOR_OVERHEAD_3("Graardor_-_Break_their_bones.wav"),
    GRAARDOR_OVERHEAD_4("Graardor_-_CHAAARGE!.wav"),
    GRAARDOR_OVERHEAD_5("Graardor_-_Crush_them_underfoot.wav"),
    GRAARDOR_OVERHEAD_6("Graardor_-_Death_to_our_enemies.wav"),
    GRAARDOR_OVERHEAD_7("Graardor_-_For_the_glory_of_Big_High_War_God.wav"),
    GRAARDOR_OVERHEAD_8("Graardor_-_GRRRAAAAR!.wav"),
    GRAARDOR_OVERHEAD_9("Graardor_-_Split_their_skulls.wav"),
    GRAARDOR_OVERHEAD_10("Graardor_-_We_feast_on_the_bones_of_our_enemies_tonight.wav"),
    GRAARDOR_DEATH_1("Graardor_-_Death_1.wav"),
    GRAARDOR_DEATH_2("Graardor_-_Death_2.wav"),

    // Commander Zilyana
    ZILYANA_OVERHEAD_1("Zilyana_-_All_praise_Saradomin.wav"),
    ZILYANA_OVERHEAD_2("Zilyana_-_Attack!_Find_the_Godsword.wav"),
    ZILYANA_OVERHEAD_3("Zilyana_-_Death_to_the_enemies_of_the_light.wav"),
    ZILYANA_OVERHEAD_4("Zilyana_-_Forward!_Our_allies_are_with_us.wav"),
    ZILYANA_OVERHEAD_5("Zilyana_-_Good_will_always_triumph.wav"),
    ZILYANA_OVERHEAD_6("Zilyana_-_In_the_name_of_Saradomin.wav"),
    ZILYANA_OVERHEAD_7("Zilyana_-_May_Saradomin_be_my_sword.wav"),
    ZILYANA_OVERHEAD_8("Zilyana_-_Saradomin_is_with_us.wav"),
    ZILYANA_OVERHEAD_9("Zilyana_-_Saradomin_lend_me_strength.wav"),
    ZILYANA_OVERHEAD_10("Zilyana_-_Slay_the_evil_ones.wav"),
    ZILYANA_DEATH_1("Zilyana_-_Death_1.wav"),
    ZILYANA_DEATH_2("Zilyana_-_Death_2.wav"),
    ZILYANA_DEATH_3("Zilyana_-_Death_3.wav"),
    ZILYANA_HURT_1("Zilyana_-_Hurt_1.wav"),
    ZILYANA_HURT_2("Zilyana_-_Hurt_2.wav"),
    ZILYANA_HURT_3("Zilyana_-_Hurt_3.wav"),
    ZILYANA_HURT_4("Zilyana_-_Hurt_4.wav"),

    // Kree'arra
    KREEARRA_KRAAW("Kree'arra_-_Kraaaw!.wav"),
    KREEARRA_SKREE("Kree'arra_-_Skreeeee!.wav"),

    // K'ril Tsutsaroth
    KRIL_OVERHEAD_1("K'ril_-_Attack!.wav"),
    KRIL_OVERHEAD_2("K'ril_-_Attack_them_you_dogs.wav"),
    KRIL_OVERHEAD_3("K'ril_-_Death_to_Saradomin's_dogs.wav"),
    KRIL_OVERHEAD_4("K'ril_-_Flay_them_all.wav"),
    KRIL_OVERHEAD_5("K'ril_-_Forward.wav"),
    KRIL_OVERHEAD_6("K'ril_-_Kill_them_you_cowards.wav"),
    KRIL_OVERHEAD_7("K'ril_-_No_retreat.wav"),
    KRIL_OVERHEAD_8("K'ril_-_Rend_them_limb_from_limb.wav"),
    KRIL_OVERHEAD_9("K'ril_-_The_dark_one_will_have_their_souls.wav"),
    KRIL_OVERHEAD_10("K'ril_-_Zamorak_curse_them.wav"),
    KRIL_YARRR("K'ril_-_Yarrr.wav"),
    KRIL_DEATH("K'ril_-_Death.wav"),

    ;

    @Getter
    private final String resourceName;

    Sound(String resNam) {
        resourceName = resNam;
    }

    @Override
    public String toString() {
        return resourceName;
    }
}
